# Generated by Django 4.1.3 on 2023-01-25 15:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('created', 'Created'), ('payed', 'Payed'), ('cancelled', 'Cancelled')], default='created', editable=False, max_length=10, verbose_name='Status')),
                ('price', models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiser.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Tiser',
                'verbose_name_plural': 'Tisers',
            },
        ),
    ]
